### ISSUE TITLE
Quesrtions about the PCB

### ISSUE THREAD

**Issue by JPFrancoia** [thomo/sensornode#1]
Hi,

I looked at your project and it looks very good. I'm no expert at reading PCB design, so I figured I might ask you directly:

- Is there any way to link the Vin pin of the I2C sensor to a GPIO of the board (to limit power consumption) ?
- Is it possible to power the PCB with a battery?

I really like the compactness of the PCB, and the USB interface. It would be super practical to make a small sensor: no hanging wires since the I2C sensor is soldered directly on the board, and very easy to upgrade the code through USB (I can 3D print a case to just expose the usb).

Kind regards

**Comment by thomo** [comment]
Hi,
1) I didn't try it but I assume it should be possible. You could just try to cut the trace above pin8 of ESP which goes to the sensors and connect the senors side to GPIO2.
2) Sure - please check the SensorNodeCat board (in folder board). It is even more compact.

**Comment by JPFrancoia** [comment]
Perfect, thank you very much!
